- CHANGELOG.md
- frontend/src/app/eq-assets/eq-assets.ts
- frontend/src/views/viewers/SpellAnimationViewer.vue
- package.json
* Fixed bug that prevented all previews from showing properly
> [Spell Preview] Fix bug preventing spell previews from completely loading

- CHANGELOG.md
- frontend/src/app/video-viewer/video-viewer.ts
- frontend/src/components/eq-ui/EQWindowSimple.vue
- frontend/src/components/eq-ui/styles/eq-ui.css
- frontend/src/views/viewers/EmitterViewer.vue
- frontend/src/views/viewers/PlayerAnimationViewer.vue
- frontend/src/views/viewers/RaceViewer.vue
- frontend/src/views/viewers/SpellAnimationViewer.vue
- package.json
* Various UI tweaks to viewers for a much cleaner, simple user experience
> [Spells] Viewer UI Tweaks

- CHANGELOG.md
- frontend/src/views/quest-api-explorer/QuestApiExplorer.vue
- package.json
Implemented searching by method param. [#23](https://github.com/Akkadius/spire/issues/23)
> [Quest API] Implemented searching by method param

- frontend/src/app/npcs.ts
- frontend/src/components/preview/NpcSpellPreview.vue
- frontend/src/components/selectors/SpellPreviewTableSelector.vue
- frontend/src/components/selectors/SpellSelector.vue
- frontend/src/router.ts
- frontend/src/routes.ts
- frontend/src/views/items/components/ItemSpellEffectSelector.vue
- frontend/src/views/items/components/ItemSpellPreviewTableSelector.vue
- frontend/src/views/merchants/components/MerchantlistEntryEdit.vue
- frontend/src/views/npcs/NpcSpellListEditor.vue
- frontend/src/views/npcs/NpcSpellsEditor.vue
- frontend/src/views/spells/SpellEditor.vue
- frontend/src/views/spells/Spells.vue
* Automatic spell type detection
* List previews
* Manage NPC spell sets fully
* NPC preview
* Search
* Spell list nesting highlighting
* Table pagination
> [1.13.7] [NPC Spells Editor] Early alpha release of NPC spells editor

- CHANGELOG.md
- frontend/src/app/loot.ts
- frontend/src/app/merchants.ts
- frontend/src/components/eq-ui/EqCashDisplay.vue
- frontend/src/components/layout/Navbar.vue
- frontend/src/components/preview/EQLootCardPreview.vue
- frontend/src/components/subeditors/LootSubEditor.vue
- frontend/src/router.ts
- frontend/src/routes.ts
- frontend/src/views/loot/Loot.vue
- frontend/src/views/npcs/NpcSpellsEditor.vue
- frontend/src/views/tasks/TaskEditor.vue
- frontend/src/views/tasks/components/TaskPreview.vue
- frontend/src/views/tasks/components/TaskTimerCountdown.vue
- package.json
Adds support for task requisite activity ID.
Tasks for example in Dragons of Norrath have activities that are not sequential and can be unlocked early in task progression. This update adds support on the editor side.
> [2.1.0] [Task Editor] Task Preview Requisite Activity ID

- .vscode/launch.json
This adds support for pressing F5 in vscode and debugging spire
> Added debugging in vscode

- internal/questapi/file_parse_perl_methods.go
- The quest and Mob method in Perl were using `const int` as return type, so they weren't being picked up.
> [Bug Fix] Fix GetItemStat() not showing

- CHANGELOG.md
- frontend/src/app/video-viewer/video-viewer.ts
- frontend/src/views/admin/tools/DatabaseBackup.vue
- frontend/src/views/items/ItemEditor.vue
- frontend/src/views/spells/SpellEditor.vue
* **Spell Editor** ID selector input now only engages on input focus instead of hover.
* **Video Renderer** Optimizations made to the video renderer to fully destroy video elements when out of view, not just stop them from playing. This will help with memory usage and performance. This will benefit all video render standalone utilities and sub-editor panes.
* **Database Backup (Spire Admin)** Fix an issue with database backup form where compress would reset other selections.
> [3.3.4] Release

- CHANGELOG.md
- frontend/src/app/video-viewer/video-viewer.ts
- frontend/src/assets/css/global.css
- frontend/src/views/asset-viewers/EmitterViewer.vue
- frontend/src/views/asset-viewers/PlayerAnimationViewer.vue
- frontend/src/views/asset-viewers/SpellAnimationViewer.vue
- frontend/src/views/spells/components/SpellAnimationSelector.vue
- frontend/src/views/spells/components/SpellCastingAnimationSelector.vue
- frontend/src/views/spells/components/SpellNimbusAnimationSelector.vue
- package.json
* **Video Renderer** Additional performance, responsiveness, memory, and stability improvements to the video renderer.
> [Release] 3.3.5

- .gitignore
- CHANGELOG.md
- boot/inject_commands.go
- boot/wire_gen.go
- frontend/src/views/admin/server-update/UpdateReleases.vue
- frontend/src/views/server-developer/Release.vue
- frontend/src/views/server-developer/Releases.vue
- internal/console/cmd/generate_models_cmd.go
- internal/console/cmd/spire_crash_analytics.go
- internal/crashreporting/fingerprint.go
- internal/eqemuanalytics/analytics_controller.go
- internal/eqemuanalytics/releases.go
- internal/models/spire_server_crash_report.go
- package.json
* **Crash Analytics** Added fingerprinting to crash analytics to help identify duplicate crashes.
* **Crash Analytics** Add Discord webhook to crash analytics to notify developers of new unique crashes.
* **Server Updater** Added unique crash counts to the server updater page within Spire Admin
> [3.4.0] Crash Analytics Fingerprinting

- CHANGELOG.md
- frontend/src/views/admin/configuration/ServerConfig.vue
- internal/eqemuserverconfig/config.go
- package.json
Related to https://github.com/EQEmu/Server/pull/3768
> [ServerConfig] UCS config block

- frontend/src/components/tools/NpcSpecialAbilities.vue
- Adds support in Special Abilities Calculator for `Immune to Assassinate` and `Immune to Headshot` abilities.
> [Feature] Add Immune to Assassinate/Headshot Abilities

- CHANGELOG.md
- frontend/src/views/admin/Dashboard.vue
- frontend/src/views/admin/components/DashboardNetworkingInfo.vue
- frontend/src/views/admin/configuration/Motd.vue
- frontend/src/views/admin/layout/AdminHeader.vue
- internal/eqemuserver/client.go
- internal/eqemuserver/controller.go
- internal/eqemuserverconfig/config.go
- internal/http/middleware/plain_request_logger.go
- package.json
* **Spire Admin** Message of the day should now be functional again
* **Spire Admin** Spire now has a server lock / unlock button and status icon that is now present in the admin header visible on all admin pages.
* **Spire Admin** The dashboard page now has a "Server Addresses" section that displays server world address and local address with copy to clipboard functionality if they are present in the server configuration.
* **Spire Admin** The dashboard page now has a "Networking Interfaces" section that displays interfaces and realtime bandwidth utilization.
* **Special Abilities Calculator** Adds support in Special Abilities Calculator for `Immune to Assassinate` and `Immune to Headshot` abilities. (Kinglykrab)
> [Release] 3.10.0

- frontend/src/components/tools/NpcSpecialAbilities.vue
- Add `Immune to Bot Aggro` and `Immune to Bot Damage`.
> [Feature] Add Immune Bot Aggro/Damage Abilities

- CHANGELOG.md
- frontend/src/views/admin/components/LauncherOptions.vue
- internal/eqemuserver/installer.go
- internal/eqemuserver/launcher.go
- internal/eqemuserverconfig/config.go
- internal/eqemuserverconfig/controller.go
- package.json
* **Spire Admin** Add the ability to make booting UCS optional in the Spire Launcher.
> [Release] 4.11.0

- CHANGELOG.md
- frontend/src/assets/css/global.css
- frontend/src/components/eq-ui/styles/eq-ui.css
- frontend/src/components/layout/ContentArea.vue
- frontend/src/views/Home.vue
- frontend/src/views/admin/components/LauncherOptions.vue
- frontend/src/views/connections/Connections.vue
- frontend/src/views/user/UserManagement.vue
- package.json
* **Dark Mode** Ship the initial dark mode theme for Spire Admin, requires that you have dark mode enabled in your system preferences.
> [Release] 4.13.0 - Dark Mode

- CHANGELOG.md
- frontend/src/components/eq-ui/EQWindowSimple.vue
- frontend/src/components/eq-ui/styles/eq-ui.css
- frontend/src/views/admin/ZoneServers.vue
- frontend/src/views/admin/components/DashboardCpuInfo.vue
- frontend/src/views/admin/components/DashboardProcessCounts.vue
- frontend/src/views/admin/components/PlayersOnlineComponent.vue
- frontend/src/views/admin/layout/AdminHeader.vue
- internal/eqemuserver/client.go
- internal/eqemuserver/controller.go
- package.json
* **Spire Admin** Add top level server processes "Show Stats" toggle.
* **Spire Admin** Improve zoneserver page updating and performance.
* **Spire Admin** When there are more than 50 players online, stop updating the player list on the main page.
* **Spire Admin** Improve admin header performance by utilizing newer EQEmu Server API endpoints.
[![image.png](https://i.postimg.cc/FHxXrPkt/image.png)](https://postimg.cc/BjtVNBCN)
> [Spire Admin] Improvements 4.19.0

- containers/workspace/Dockerfile
- docker-compose.yml
- go.mod
Just some updates to move past some upstream issues in stand-alone
> Update go version in stand-alone

- frontend/src/views/admin/server-update/ServerUpdate.vue
- internal/console/cmd/test_filesystem_cmd.go
- internal/eqemuserver/updater.go
- internal/models/db_version.go
Support custom database versions from https://github.com/EQEmu/Server/pull/4892
No custom version set:
Custom version set:
Navigation collapsed:
> [Server Admin] Display custom database version if set

- docs/swagger.json
- docs/swagger.yaml
- frontend/src/app/api/models/models-player-event-log-setting.ts
- frontend/src/views/admin/player-event-logs/PlayerEventLogSettings.vue
- internal/eqemuserver/controller.go
> [Logs] Add `etl_enabled` to Player Event Log Settings

- CHANGELOG.md
- frontend/src/views/spells/SpellEditor.vue
- frontend/src/views/spells/components/SpellSpaFormulasPane.vue
- package.json
Fix typo in setting time
Fix spacing
Remove unneeded code
> [Release] 4.20.1

- CHANGELOG.md
- internal/permissions/service.go
- package.json
**Spire Admin** Add permission settings for player event log ETL settings.
> [Release] 4.20.2

- frontend/src/views/admin/player-event-logs/components/PlayerEventDisplayComponent.vue
Remove charges as those values are not exported
> [Event Logs] Cleanup groundspawn pickup

- frontend/src/app/constants/eq-spell-constants.ts
- frontend/src/views/spells/SpellEditor.vue
- frontend/src/views/spells/components/SpellSpaFormulasPane.vue
Add ability to select formula from known formulas window pane
Current behavior:
New behavior:
> [Spells] Add spell formula selector
